[package]
name = "batman"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
gtk4 = { version = "0.9.6", features = ["v4_16"] }
gtk4-layer-shell = "0.5.0"
notify-rust = "4.11.7"
sass-rs = "0.2.2"
